# Header
menu:
  Home: /
  Archives: /archives
  About Me: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- link
links:
- name: Friends' Blogs
  links:
  - name: code風景區
    url: http://codingsimplifylife.blogspot.tw/
  - name: Chino's
    url: https://chino.taipei/
  - name: Coding Beans
    url: http://codingbeans.blogspot.tw/

# Miscellaneous
google_analytics: UA-49513664-2
favicon: /favicon.ico
twitter: 
google_plus: https://plus.google.com/+%E8%98%87%E5%A4%9A%E9%96%80domen
fb_admins:
fb_app_id:
