# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: 
favicon: /favicon.ico
twitter: 
google_plus: https://plus.google.com/+%E8%98%87%E5%A4%9A%E9%96%80domen
fb_admins:
fb_app_id:
